trigger:
  - main

stages:
  - stage: WarmUp
    jobs:
      - deployment: WarmUp
        displayName: Warming Up
        pool: default
        environment:
          name: Test
          resourceType: virtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: docker compose -f wt.yml up -d
                  displayName: Warming Up
      - deployment: CleanUp
        displayName: Cleaning Up
        pool: default
        environment:
          name: Test
          resourceType: virtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: docker compose -f wt.yml down -v
                  displayName: Cleaning up